//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asi.asicentral.web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("asi.asicentral.web.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comapny.
        /// </summary>
        public static string AddCompany {
            get {
                return ResourceManager.GetString("AddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Inactive?.
        /// </summary>
        public static string ColumnIsInactive {
            get {
                return ResourceManager.GetString("ColumnIsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Image.
        /// </summary>
        public static string ColumnLargeImage {
            get {
                return ResourceManager.GetString("ColumnLargeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ColumnProductName {
            get {
                return ResourceManager.GetString("ColumnProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Image.
        /// </summary>
        public static string ColumnSmallImage {
            get {
                return ResourceManager.GetString("ColumnSmallImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        public static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to delete the item.
        /// </summary>
        public static string DeleteTooltip {
            get {
                return ResourceManager.GetString("DeleteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Stamp.
        /// </summary>
        public static string DieStamp {
            get {
                return ResourceManager.GetString("DieStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Embroidery.
        /// </summary>
        public static string DirectEmbroidery {
            get {
                return ResourceManager.GetString("DirectEmbroidery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreements.
        /// </summary>
        public static string DistributorAgreements {
            get {
                return ResourceManager.GetString("DistributorAgreements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Lines.
        /// </summary>
        public static string DistributorAppProductLines {
            get {
                return ResourceManager.GetString("DistributorAppProductLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types of Accounts.
        /// </summary>
        public static string DistributorAppTypesOfAccount {
            get {
                return ResourceManager.GetString("DistributorAppTypesOfAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to edit the item.
        /// </summary>
        public static string EditToolTip {
            get {
                return ResourceManager.GetString("EditToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engraving.
        /// </summary>
        public static string Engraving {
            get {
                return ResourceManager.GetString("Engraving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etching.
        /// </summary>
        public static string Etching {
            get {
                return ResourceManager.GetString("Etching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must be a number.
        /// </summary>
        public static string FieldIMustBeNumber {
            get {
                return ResourceManager.GetString("FieldIMustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foil Stamping.
        /// </summary>
        public static string FoilStamping {
            get {
                return ResourceManager.GetString("FoilStamping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four Color Process.
        /// </summary>
        public static string FourColourProcess {
            get {
                return ResourceManager.GetString("FourColourProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Colour Process.
        /// </summary>
        public static string FullColourProcess {
            get {
                return ResourceManager.GetString("FullColourProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Stamping.
        /// </summary>
        public static string HotStamping {
            get {
                return ResourceManager.GetString("HotStamping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithography.
        /// </summary>
        public static string Lithography {
            get {
                return ResourceManager.GetString("Lithography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Decorating Method.
        /// </summary>
        public static string OtherDecoratingMethod {
            get {
                return ResourceManager.GetString("OtherDecoratingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Decorating Method Name.
        /// </summary>
        public static string OtherDecoratingMethodName {
            get {
                return ResourceManager.GetString("OtherDecoratingMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad Print.
        /// </summary>
        public static string PadPrint {
            get {
                return ResourceManager.GetString("PadPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGR Maintenance.
        /// </summary>
        public static string SGRMaintenanceLink {
            get {
                return ResourceManager.GetString("SGRMaintenanceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SilkScreen.
        /// </summary>
        public static string SilkScreen {
            get {
                return ResourceManager.GetString("SilkScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASI Store Admin.
        /// </summary>
        public static string StoreAdminLink {
            get {
                return ResourceManager.GetString("StoreAdminLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders processed through the store.
        /// </summary>
        public static string StoreAdminOrders {
            get {
                return ResourceManager.GetString("StoreAdminOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Products driving the store.
        /// </summary>
        public static string StoreAdminProducts {
            get {
                return ResourceManager.GetString("StoreAdminProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string StoreApplication {
            get {
                return ResourceManager.GetString("StoreApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASI#.
        /// </summary>
        public static string StoreASINumber {
            get {
                return ResourceManager.GetString("StoreASINumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        public static string StoreBillingAddress {
            get {
                return ResourceManager.GetString("StoreBillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Date.
        /// </summary>
        public static string StoreClosedDate {
            get {
                return ResourceManager.GetString("StoreClosedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string StoreCompany {
            get {
                return ResourceManager.GetString("StoreCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string StoreCompanyName {
            get {
                return ResourceManager.GetString("StoreCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date must not be after end date.
        /// </summary>
        public static string StoreDateErrorMessage {
            get {
                return ResourceManager.GetString("StoreDateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        public static string StoreDateOrderCreated {
            get {
                return ResourceManager.GetString("StoreDateOrderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string StoreEmail {
            get {
                return ResourceManager.GetString("StoreEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string StoreItem {
            get {
                return ResourceManager.GetString("StoreItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string StoreName {
            get {
                return ResourceManager.GetString("StoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Amount.
        /// </summary>
        public static string StoreOrderAmount {
            get {
                return ResourceManager.GetString("StoreOrderAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Closed Date.
        /// </summary>
        public static string StoreOrderClosedDate {
            get {
                return ResourceManager.GetString("StoreOrderClosedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string StoreOrderDate {
            get {
                return ResourceManager.GetString("StoreOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Id.
        /// </summary>
        public static string StoreOrderID {
            get {
                return ResourceManager.GetString("StoreOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string StorePhone {
            get {
                return ResourceManager.GetString("StorePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string StoreProduct {
            get {
                return ResourceManager.GetString("StoreProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string StoreQuantity {
            get {
                return ResourceManager.GetString("StoreQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string StoreSearchButton {
            get {
                return ResourceManager.GetString("StoreSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a date range to search:.
        /// </summary>
        public static string StoreSearchMessage {
            get {
                return ResourceManager.GetString("StoreSearchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        public static string StoreStatus {
            get {
                return ResourceManager.GetString("StoreStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string StoreStatusClosed {
            get {
                return ResourceManager.GetString("StoreStatusClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string StoreStatusOpened {
            get {
                return ResourceManager.GetString("StoreStatusOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributor Application.
        /// </summary>
        public static string StoreTitleDistributorApplication {
            get {
                return ResourceManager.GetString("StoreTitleDistributorApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazines - {0}.
        /// </summary>
        public static string StoreTitleMagazinesApplication {
            get {
                return ResourceManager.GetString("StoreTitleMagazinesApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Carts.
        /// </summary>
        public static string StoreTitleOpenCarts {
            get {
                return ResourceManager.GetString("StoreTitleOpenCarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string StoreTitleOrders {
            get {
                return ResourceManager.GetString("StoreTitleOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Application.
        /// </summary>
        public static string StoreTitleSupplierApplication {
            get {
                return ResourceManager.GetString("StoreTitleSupplierApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Annual Sales Volume.
        /// </summary>
        public static string StoreTotalAnnualSalesVolume {
            get {
                return ResourceManager.GetString("StoreTotalAnnualSalesVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sublimination.
        /// </summary>
        public static string Sublimination {
            get {
                return ResourceManager.GetString("Sublimination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Contacts.
        /// </summary>
        public static string SupplierAppCompanyContacts {
            get {
                return ResourceManager.GetString("SupplierAppCompanyContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods of Imprinting.
        /// </summary>
        public static string SupplierAppMethodsOfImprinting {
            get {
                return ResourceManager.GetString("SupplierAppMethodsOfImprinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Force.
        /// </summary>
        public static string SupplierAppSalesForce {
            get {
                return ResourceManager.GetString("SupplierAppSalesForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string TitleAddCategory {
            get {
                return ResourceManager.GetString("TitleAddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Company.
        /// </summary>
        public static string TitleAddCompany {
            get {
                return ResourceManager.GetString("TitleAddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        public static string TitleAddProduct {
            get {
                return ResourceManager.GetString("TitleAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASI Store Admin.
        /// </summary>
        public static string TitleASIStoreAdmin {
            get {
                return ResourceManager.GetString("TitleASIStoreAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string TitleCategories {
            get {
                return ResourceManager.GetString("TitleCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category.
        /// </summary>
        public static string TitleEditCategory {
            get {
                return ResourceManager.GetString("TitleEditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Company.
        /// </summary>
        public static string TitleEditCompany {
            get {
                return ResourceManager.GetString("TitleEditCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product.
        /// </summary>
        public static string TitleEditProduct {
            get {
                return ResourceManager.GetString("TitleEditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Companies.
        /// </summary>
        public static string TitleListCompanies {
            get {
                return ResourceManager.GetString("TitleListCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
    }
}
