//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asi.asicentral.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Catalogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Catalogs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("asi.asicentral.Resources.Catalogs", typeof(Catalogs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork.
        /// </summary>
        public static string Artwork {
            get {
                return ResourceManager.GetString("Artwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would like to EMAIL Camera Ready Artwork to &lt;a href=&quot;mailto:catalogart@asicentral.com&quot;&gt;catalogart@asicentral.com&lt;/a&gt;.
        /// </summary>
        public static string ArtworkOptionEMAIL {
            get {
                return ResourceManager.GetString("ArtworkOptionEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will enter text to print on catalog.
        /// </summary>
        public static string ArtworkOptionPRINT {
            get {
                return ResourceManager.GetString("ArtworkOptionPRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would like to UPLOAD Camera Ready Artwork.
        /// </summary>
        public static string ArtworkOptionUPLOAD {
            get {
                return ResourceManager.GetString("ArtworkOptionUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover.
        /// </summary>
        public static string CoverOptions {
            get {
                return ResourceManager.GetString("CoverOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact Repeat.
        /// </summary>
        public static string ExactRepeat {
            get {
                return ResourceManager.GetString("ExactRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported file formats (pdf, ai, eps, jpg, pjpeg).
        /// </summary>
        public static string FileFormat {
            get {
                return ResourceManager.GetString("FileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a file to continue further.
        /// </summary>
        public static string FileUplaod {
            get {
                return ResourceManager.GetString("FileUplaod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Cover.
        /// </summary>
        public static string FrontCover {
            get {
                return ResourceManager.GetString("FrontCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Color.
        /// </summary>
        public static string FullColor {
            get {
                return ResourceManager.GetString("FullColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Supplement.
        /// </summary>
        public static string GiftSupplement {
            get {
                return ResourceManager.GetString("GiftSupplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create sales with this compact catalog that’s perfect for leave-behinds and mailers..
        /// </summary>
        public static string IdeaShowcaseDescription {
            get {
                return ResourceManager.GetString("IdeaShowcaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create sales with this compact catalog that’s perfect for leave-behinds and mailers..
        /// </summary>
        public static string IdeaShowcaseSchoolsDescription {
            get {
                return ResourceManager.GetString("IdeaShowcaseSchoolsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprint Instructions.
        /// </summary>
        public static string ImprintInstructions {
            get {
                return ResourceManager.GetString("ImprintInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 1.
        /// </summary>
        public static string Line1 {
            get {
                return ResourceManager.GetString("Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 2.
        /// </summary>
        public static string Line2 {
            get {
                return ResourceManager.GetString("Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 3.
        /// </summary>
        public static string Line3 {
            get {
                return ResourceManager.GetString("Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 4.
        /// </summary>
        public static string Line4 {
            get {
                return ResourceManager.GetString("Line4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 5.
        /// </summary>
        public static string Line5 {
            get {
                return ResourceManager.GetString("Line5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 6.
        /// </summary>
        public static string Line6 {
            get {
                return ResourceManager.GetString("Line6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For decades, the highly regarded Media File has been used by distributors as their single most powerful sales tool..
        /// </summary>
        public static string MediaFileDescription {
            get {
                return ResourceManager.GetString("MediaFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum order of XYZ catalogs.
        /// </summary>
        public static string MinQuantity {
            get {
                return ResourceManager.GetString("MinQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Repeat.
        /// </summary>
        public static string ModifiedRepeat {
            get {
                return ResourceManager.GetString("ModifiedRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Artwork - one time $25.00 charge.
        /// </summary>
        public static string NewArtwork {
            get {
                return ResourceManager.GetString("NewArtwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Imprint.
        /// </summary>
        public static string NoImprint {
            get {
                return ResourceManager.GetString("NoImprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schools Cover.
        /// </summary>
        public static string SchoolsCover {
            get {
                return ResourceManager.GetString("SchoolsCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Method.
        /// </summary>
        public static string ShippingMethod {
            get {
                return ResourceManager.GetString("ShippingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destined to become your most indispensable and versatile selling tool for the second selling season..
        /// </summary>
        public static string SpectrumCelebrationDescription {
            get {
                return ResourceManager.GetString("SpectrumCelebrationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum is your most indispensable and versatile selling tool..
        /// </summary>
        public static string SpectrumDescription {
            get {
                return ResourceManager.GetString("SpectrumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Cover.
        /// </summary>
        public static string StandardCover {
            get {
                return ResourceManager.GetString("StandardCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dedicated to apparel, the most popular product category in the promotional products industry!.
        /// </summary>
        public static string TheApparelCatalogNEWFORFALL2015 {
            get {
                return ResourceManager.GetString("TheApparelCatalogNEWFORFALL2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our most upscale, elegant catalog containing an impressive collection of timeless gifts..
        /// </summary>
        public static string TheGiftBookDescription {
            get {
                return ResourceManager.GetString("TheGiftBookDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Professional Buyer’s Guide is your go-to catalogue for the Canadian marketplace..
        /// </summary>
        public static string TheProfessionalBuyersGuideDescription {
            get {
                return ResourceManager.GetString("TheProfessionalBuyersGuideDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
