//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asi.asicentral.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ESPAdvertising {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ESPAdvertising() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("asi.asicentral.Resources.ESPAdvertising", typeof(ESPAdvertising).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Ad.
        /// </summary>
        public static string Banner_Ad {
            get {
                return ResourceManager.GetString("Banner_Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESP Online Search Screen Advertising Call attention to your latest or best selling product..
        /// </summary>
        public static string BannerTileTowerDesc {
            get {
                return ResourceManager.GetString("BannerTileTowerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload image for Buddy List.
        /// </summary>
        public static string Buddy_Error {
            get {
                return ResourceManager.GetString("Buddy_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buddy List $199/mo..
        /// </summary>
        public static string Buddy_List {
            get {
                return ResourceManager.GetString("Buddy_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to budget ?.
        /// </summary>
        public static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories_Ad {
            get {
                return ResourceManager.GetString("Categories_Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one category should be entered.
        /// </summary>
        public static string Categories_Error {
            get {
                return ResourceManager.GetString("Categories_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All categories should be separated by (;).
        /// </summary>
        public static string Categories_Val {
            get {
                return ResourceManager.GetString("Categories_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one product..
        /// </summary>
        public static string ClearanceNewRush_Error {
            get {
                return ResourceManager.GetString("ClearanceNewRush_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a massive impression on all distributors searching ESP Online™..
        /// </summary>
        public static string ClearanceNewSpecialsDesc {
            get {
                return ResourceManager.GetString("ClearanceNewSpecialsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dollars.
        /// </summary>
        public static string Dollars {
            get {
                return ResourceManager.GetString("Dollars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload Banner Ad for result page.
        /// </summary>
        public static string Error_ResultBannerPath {
            get {
                return ResourceManager.GetString("Error_ResultBannerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload Tile Ad for result page.
        /// </summary>
        public static string Error_ResultTilePath {
            get {
                return ResourceManager.GetString("Error_ResultTilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload Tower Ad for result page.
        /// </summary>
        public static string Error_ResultTowerPath {
            get {
                return ResourceManager.GetString("Error_ResultTowerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload Banner Ad for search page.
        /// </summary>
        public static string Error_SearchBannerPath {
            get {
                return ResourceManager.GetString("Error_SearchBannerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload Tile Ad for search page.
        /// </summary>
        public static string Error_SearchTilePath {
            get {
                return ResourceManager.GetString("Error_SearchTilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload Tower Ad for search page.
        /// </summary>
        public static string Error_SearchTowerPath {
            get {
                return ResourceManager.GetString("Error_SearchTowerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Event Planner offers one-stop shopping for distributors looking for event merchandise..
        /// </summary>
        public static string EventPlannerDesc {
            get {
                return ResourceManager.GetString("EventPlannerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported file formats (pdf, ai, eps, jpg,pjpeg).
        /// </summary>
        public static string FileFormat_1 {
            get {
                return ResourceManager.GetString("FileFormat_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported file formats (gif, jpef, mpeg, x-shockwave-flash).
        /// </summary>
        public static string FileFormat_2 {
            get {
                return ResourceManager.GetString("FileFormat_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported file formats (mpg, mpeg, mov, wmv,avi).
        /// </summary>
        public static string FileFormat_3 {
            get {
                return ResourceManager.GetString("FileFormat_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported file formats(zip).
        /// </summary>
        public static string FileFormat_4 {
            get {
                return ResourceManager.GetString("FileFormat_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        public static string Fixed {
            get {
                return ResourceManager.GetString("Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impressions.
        /// </summary>
        public static string Impressions {
            get {
                return ResourceManager.GetString("Impressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant Messenger $450/mo..
        /// </summary>
        public static string Instant_Messanger {
            get {
                return ResourceManager.GetString("Instant_Messanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Numbers.
        /// </summary>
        public static string ItemNumbers {
            get {
                return ResourceManager.GetString("ItemNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter up to 3 Item numbers, seperated with ;.
        /// </summary>
        public static string ItemNumbers_3 {
            get {
                return ResourceManager.GetString("ItemNumbers_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter multiple item numbers, seperated with ;.
        /// </summary>
        public static string ItemNumbers_Multiple {
            get {
                return ResourceManager.GetString("ItemNumbers_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item numbers needed..
        /// </summary>
        public static string ItemNumbersNeeded {
            get {
                return ResourceManager.GetString("ItemNumbersNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        public static string LoginScreen_Date {
            get {
                return ResourceManager.GetString("LoginScreen_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose at least one date.
        /// </summary>
        public static string LoginScreen_Dates_Requried {
            get {
                return ResourceManager.GetString("LoginScreen_Dates_Requried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected {x} date(s):.
        /// </summary>
        public static string LoginScreen_Selected_Dates_Count {
            get {
                return ResourceManager.GetString("LoginScreen_Selected_Dates_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make the first impression on all distributors logging into ESP Online by placing your advertisement on the login screen..
        /// </summary>
        public static string LoginScreenDesc {
            get {
                return ResourceManager.GetString("LoginScreenDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Logo Required.
        /// </summary>
        public static string LogoLine_Error {
            get {
                return ResourceManager.GetString("LogoLine_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This powerful branding tool displays your logo every time your products are scrolled over in ESP search results..
        /// </summary>
        public static string LogoLineDesc {
            get {
                return ResourceManager.GetString("LogoLineDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogoPath.
        /// </summary>
        public static string LogoPath {
            get {
                return ResourceManager.GetString("LogoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Chat Room $750/mo..
        /// </summary>
        public static string Main_Chat_Room {
            get {
                return ResourceManager.GetString("Main_Chat_Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload image for Main Chat Room.
        /// </summary>
        public static string MainChat_Error {
            get {
                return ResourceManager.GetString("MainChat_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload image for Instant Messenger.
        /// </summary>
        public static string Messenger_Error {
            get {
                return ResourceManager.GetString("Messenger_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of.
        /// </summary>
        public static string Numberof {
            get {
                return ResourceManager.GetString("Numberof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Products.
        /// </summary>
        public static string NumberOfProducts {
            get {
                return ResourceManager.GetString("NumberOfProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are competing with &lt;strong&gt;{0} suppliers &lt;/strong&gt;in this category.
        /// </summary>
        public static string NumOfCompetitorsString {
            get {
                return ResourceManager.GetString("NumOfCompetitorsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one category..
        /// </summary>
        public static string PayForPlacement_Error {
            get {
                return ResourceManager.GetString("PayForPlacement_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose to target your advertising only to distributors searching on a particular category..
        /// </summary>
        public static string PayforPlacementDesc {
            get {
                return ResourceManager.GetString("PayforPlacementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per month.
        /// </summary>
        public static string PerMonth {
            get {
                return ResourceManager.GetString("PerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Choose where you want to appear in search results:.
        /// </summary>
        public static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Choose the way you would like to pay:.
        /// </summary>
        public static string Question2 {
            get {
                return ResourceManager.GetString("Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload image for Result Banner Ad.
        /// </summary>
        public static string ResultBanner_Error {
            get {
                return ResourceManager.GetString("ResultBanner_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload image for Result Tile Ad.
        /// </summary>
        public static string ResultTile_Error {
            get {
                return ResourceManager.GetString("ResultTile_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload image for Result Tower Ad.
        /// </summary>
        public static string ResultTower_Error {
            get {
                return ResourceManager.GetString("ResultTower_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tower Ad.
        /// </summary>
        public static string ResultTowerAd {
            get {
                return ResourceManager.GetString("ResultTowerAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload image for Search Banner Ad.
        /// </summary>
        public static string SearchBanner_Error {
            get {
                return ResourceManager.GetString("SearchBanner_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload image for Search Tile Ad.
        /// </summary>
        public static string SearchTile_Error {
            get {
                return ResourceManager.GetString("SearchTile_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload image for Search Tower Ad.
        /// </summary>
        public static string SearchTower_Error {
            get {
                return ResourceManager.GetString("SearchTower_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Ad.
        /// </summary>
        public static string Title_Ad {
            get {
                return ResourceManager.GetString("Title_Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tower Ad.
        /// </summary>
        public static string Tower_Ad {
            get {
                return ResourceManager.GetString("Tower_Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People remember only 10% of what they see, and only 20% of what they hear, but 50% of what they see AND hear..
        /// </summary>
        public static string VideoDesc {
            get {
                return ResourceManager.GetString("VideoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is CPM?.
        /// </summary>
        public static string WhatisCPM {
            get {
                return ResourceManager.GetString("WhatisCPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ESP Rankings.
        /// </summary>
        public static string YourESPRankings {
            get {
                return ResourceManager.GetString("YourESPRankings", resourceCulture);
            }
        }
    }
}
