//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asi.asicentral.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ESPWebsites {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ESPWebsites() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("asi.asicentral.Resources.ESPWebsites", typeof(ESPWebsites).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter collection.
        /// </summary>
        public static string Error_Collections {
            get {
                return ResourceManager.GetString("Error_Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter up to 9 items separated using &apos;;&apos;.
        /// </summary>
        public static string Error_Items {
            get {
                return ResourceManager.GetString("Error_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themed Product Niche Catalogs will promote the products you’d like to feature on ESP Website’s home page..
        /// </summary>
        public static string FeaturedProductsDesc {
            get {
                return ResourceManager.GetString("FeaturedProductsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only following formats are allowed. [pdf, ai, eps, jpg,pjpeg].
        /// </summary>
        public static string FileFormat_1 {
            get {
                return ResourceManager.GetString("FileFormat_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only following formats are allowed. [gif, jpeg, mpeg, x-shockwave-flash].
        /// </summary>
        public static string FileFormat_2 {
            get {
                return ResourceManager.GetString("FileFormat_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ESP Websites Network delivers your product details to millions of end-buyers and thousands of distributors..
        /// </summary>
        public static string IntroductoryOfferDesc {
            get {
                return ResourceManager.GetString("IntroductoryOfferDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemNumber.
        /// </summary>
        public static string ItemNumber {
            get {
                return ResourceManager.GetString("ItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LargeImage.
        /// </summary>
        public static string LargeImage {
            get {
                return ResourceManager.GetString("LargeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload a large image..
        /// </summary>
        public static string LargeImageErr {
            get {
                return ResourceManager.GetString("LargeImageErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Months.
        /// </summary>
        public static string NumberofMonths {
            get {
                return ResourceManager.GetString("NumberofMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Websites.
        /// </summary>
        public static string NumberofWebsites {
            get {
                return ResourceManager.GetString("NumberofWebsites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to corporation.
        /// </summary>
        public static string Option_Corporation {
            get {
                return ResourceManager.GetString("Option_Corporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitizing.
        /// </summary>
        public static string Option_Digitziing {
            get {
                return ResourceManager.GetString("Option_Digitziing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embroidery.
        /// </summary>
        public static string Option_Embroidery {
            get {
                return ResourceManager.GetString("Option_Embroidery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engraving.
        /// </summary>
        public static string Option_Engraving {
            get {
                return ResourceManager.GetString("Option_Engraving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat Transfer.
        /// </summary>
        public static string Option_HeatTransfer {
            get {
                return ResourceManager.GetString("Option_HeatTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to individual.
        /// </summary>
        public static string Option_Individual {
            get {
                return ResourceManager.GetString("Option_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLC proprietorship.
        /// </summary>
        public static string Option_LLCProprietorship {
            get {
                return ResourceManager.GetString("Option_LLCProprietorship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monogramming.
        /// </summary>
        public static string Option_Monogramming {
            get {
                return ResourceManager.GetString("Option_Monogramming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Option_No {
            get {
                return ResourceManager.GetString("Option_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Option_Other {
            get {
                return ResourceManager.GetString("Option_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partnership.
        /// </summary>
        public static string Option_Partnership {
            get {
                return ResourceManager.GetString("Option_Partnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Printing.
        /// </summary>
        public static string Option_ScreenPrinting {
            get {
                return ResourceManager.GetString("Option_ScreenPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sublimation.
        /// </summary>
        public static string Option_Sublimation {
            get {
                return ResourceManager.GetString("Option_Sublimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Option_Yes {
            get {
                return ResourceManager.GetString("Option_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most major search engines carry paid placement listings guaranteeing advertisers a high ranking, usually in relation to desired words..
        /// </summary>
        public static string PayForPlacementDesc {
            get {
                return ResourceManager.GetString("PayForPlacementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 349.
        /// </summary>
        public static string ProductCollections_Cost {
            get {
                return ResourceManager.GetString("ProductCollections_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 999.
        /// </summary>
        public static string ProductCollections_DiscountedCost {
            get {
                return ResourceManager.GetString("ProductCollections_DiscountedCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PromoMart.com and SuccessfulPromotions.com Product Spotlights help promote your hottest products with a unique advertisement on the home page..
        /// </summary>
        public static string ProductSpotlightDesc {
            get {
                return ResourceManager.GetString("ProductSpotlightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which best describes your company?.
        /// </summary>
        public static string Question_BestCompany {
            get {
                return ResourceManager.GetString("Question_BestCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which method(s) of imprinting do you offer?.
        /// </summary>
        public static string Question_MethodsOfImpringting {
            get {
                return ResourceManager.GetString("Question_MethodsOfImpringting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your company a union member?.
        /// </summary>
        public static string Question_UnionMember {
            get {
                return ResourceManager.GetString("Question_UnionMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmallImage.
        /// </summary>
        public static string SmallImage {
            get {
                return ResourceManager.GetString("SmallImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload a small image..
        /// </summary>
        public static string SmallImageErr {
            get {
                return ResourceManager.GetString("SmallImageErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Around Image.
        /// </summary>
        public static string TextAroundImage {
            get {
                return ResourceManager.GetString("TextAroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextUnderImage.
        /// </summary>
        public static string TextUnderImage {
            get {
                return ResourceManager.GetString("TextUnderImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Large Image.
        /// </summary>
        public static string UploadLargeImage {
            get {
                return ResourceManager.GetString("UploadLargeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Small Image.
        /// </summary>
        public static string UploadSmallImage {
            get {
                return ResourceManager.GetString("UploadSmallImage", resourceCulture);
            }
        }
    }
}
