//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asi.asicentral.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("asi.asicentral.Resources.ProductDescriptions", typeof(ProductDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advantages magazine is written especially for the promotional products sales professional. Advantages can help you sell more..
        /// </summary>
        public static string ProductAdvantages {
            get {
                return ResourceManager.GetString("ProductAdvantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advantages magazine is written especially for the promotional products sales professional..
        /// </summary>
        public static string ProductAdvantagesAdvertising {
            get {
                return ResourceManager.GetString("ProductAdvantagesAdvertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASI SalesPro&lt;sup&gt;&amp;trade;&lt;/sup&gt; powered by Oracle&lt;sup&gt;&amp;reg;&lt;/sup&gt; is the best sales database solution to power your sales team. Now in seconds you can implement a simple strategy for managing your company’s interactions with customers, clients and sales prospects. Store all of your notes and customer contact information, set appointments and follow-ups, send emails with personalized data and track who opened them..
        /// </summary>
        public static string ProductASISalesPro {
            get {
                return ResourceManager.GetString("ProductASISalesPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by Oracle and customized by ASI just for the promotional products industry, ASI SmartSales will give you more customer insights than you’ve ever had before. Plus, you’ll be able to develop strategies and tactics that will strengthen your relationships and better penetrate your accounts..
        /// </summary>
        public static string ProductASISmartSales {
            get {
                return ResourceManager.GetString("ProductASISmartSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESP Online Search Screen Advertising Call attention to your latest or best selling product..
        /// </summary>
        public static string ProductBannerTileTower {
            get {
                return ResourceManager.GetString("ProductBannerTileTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a massive impression on all distributors searching ESP Online&lt;sup&gt;&amp;trade;&lt;/sup&gt;..
        /// </summary>
        public static string ProductClearanceNewRush {
            get {
                return ResourceManager.GetString("ProductClearanceNewRush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Stores™ - powered by ESP Websites™ - is the unique eCommerce solution designed as a stand-alone online shop for special events, niche markets, holidays or your top customers – the possibilities are virtually endless!.
        /// </summary>
        public static string ProductCompanyStore {
            get {
                return ResourceManager.GetString("ProductCompanyStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counselor&apos;s &quot;State of the Industry&quot; statistics are the industry&apos;s benchmark..
        /// </summary>
        public static string ProductCounselor {
            get {
                return ResourceManager.GetString("ProductCounselor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counselor has a paid circulation of 14,500. This monthly magazine reaches C-level distributors and is often referred to as the “Bible of the promotional products industry.&quot; All the Top 40 ASI Counselor has a paid circulation of 14,500. This monthly magazine reaches C-level distributors and is often referred to as the “Bible of the promotional products industry.&quot; All the Top 40 ASI Distributors receive copies of Counselor..
        /// </summary>
        public static string ProductCounselorAdvertising {
            get {
                return ResourceManager.GetString("ProductCounselorAdvertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The $19.4 billion advertising specialty industry is ready for you with a membership package tailored especially for commercial decorators! As an ASI&lt;sup&gt;&amp;reg;&lt;/sup&gt; member, you are provided with exclusive benefits – top industry information, affiliate discounts and savings, business tools and software, world class education and services other industry organizations do not provide. Start growing more business right now by selecting the membership package that’s right for you..
        /// </summary>
        public static string ProductDualforDistributor {
            get {
                return ResourceManager.GetString("ProductDualforDistributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send your latest products, specials, closeouts and more to 60,000 ASI members and non-members with ASI’s direct email advertising service, EmailExpress. Our email service allows distributors to request catalogs, samples and allows you to forward a distributor EmailExpress version to end-buyers. EmailExpress features informative ROI reports, which give you real-time data on delivery, clicks, forwards and buyer friendly requests in an easy-to-read format..
        /// </summary>
        public static string ProductEmailExpress {
            get {
                return ResourceManager.GetString("ProductEmailExpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESP Websites are everything that a website should be – functional, user friendly, attractive and revenue generating. Powered by ESP, the websites create a realistic retail experience for your customers, motivating them to stay, enjoy and shop. And with secure online payment, you get paid faster than ever..
        /// </summary>
        public static string ProductESPWebsites {
            get {
                return ResourceManager.GetString("ProductESPWebsites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This powerful branding tool displays your logo every time your products are scrolled over in ESP&lt;sup&gt;&amp;reg;&lt;/sup&gt; search results..
        /// </summary>
        public static string ProductFeaturedBrands {
            get {
                return ResourceManager.GetString("ProductFeaturedBrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create sales with this compact catalog that’s perfect for leave-behinds and mailers. This is one of the most popular catalogs with end-buyers because it showcases a cross section of products, from standard items like pens and stress balls to unique products like rally hair and glowing ice cubes..
        /// </summary>
        public static string ProductIdeaShowcase {
            get {
                return ResourceManager.GetString("ProductIdeaShowcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create sales with this compact catalog that’s perfect for leave-behinds and mailers. This is one of the most popular catalogs with end-buyers because it showcases a cross section of products, from standard items like pens and stress balls to unique products like rally hair and glowing ice cubes..
        /// </summary>
        public static string ProductIdeaShowcaseSchools {
            get {
                return ResourceManager.GetString("ProductIdeaShowcaseSchools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ESP Websites&lt;sup&gt;&amp;trade;&lt;/sup&gt; Network delivers your product details to millions of end-buyers and thousands of distributors..
        /// </summary>
        public static string ProductIntroductoryOffer {
            get {
                return ResourceManager.GetString("ProductIntroductoryOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make the first impression on all distributors logging into ESP Online&lt;sup&gt;&amp;trade;&lt;/sup&gt; by placing your advertisement on the login screen. This valuable ad space can be filled with a static or animated gif..
        /// </summary>
        public static string ProductLoginScreenAd {
            get {
                return ResourceManager.GetString("ProductLoginScreenAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For decades, the highly regarded Media File has been used by distributors as their single most powerful sales tool. It is depended on and used throughout the year for researching and generating ideas, but most importantly, to close sales. With hundreds of pages and thousands of products, &lt;em&gt;Media File&lt;/em&gt; is the market standard..
        /// </summary>
        public static string ProductMediaFile {
            get {
                return ResourceManager.GetString("ProductMediaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose to target your advertising only to distributors searching on a particular category.  ESP is pleased to offer Pay for Placement on eight of the top spots in any of the product search categories. Obtain higher placement in ESP, leading to more sales! Act now before your spot is taken..
        /// </summary>
        public static string ProductPayforPlacement {
            get {
                return ResourceManager.GetString("ProductPayforPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most major search engines carry paid placement listings guaranteeing advertisers a high ranking, usually in relation to desired words. .
        /// </summary>
        public static string ProductPayForPlacement1 {
            get {
                return ResourceManager.GetString("ProductPayForPlacement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themed Product Niche Catalogs will promote the products you’d like to feature on ESP Website’s home page. .
        /// </summary>
        public static string ProductProductCollections {
            get {
                return ResourceManager.GetString("ProductProductCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant Messaging and Webchat are some of the most popular ways to communicate online.  These communication media are less intrusive than a phone call and take less time than an email. Webchat offers distributors and suppliers a fast and easy way to keep in touch on a platform they already use everyday. ESP Online&lt;sup&gt;&amp;trade;&lt;/sup&gt; is pleased to offer three advertising spots within PromoCafé Webchat..
        /// </summary>
        public static string ProductPromoCafeWebchat {
            get {
                return ResourceManager.GetString("ProductPromoCafeWebchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogs product - Select.
        /// </summary>
        public static string ProductSelect {
            get {
                return ResourceManager.GetString("ProductSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGR is delivered to 8,000 ASI suppliers. SGR helps promotional products suppliers run their enterprises more efficiently..
        /// </summary>
        public static string ProductSGRAdvertising {
            get {
                return ResourceManager.GetString("ProductSGRAdvertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;em&gt;Spectrum&lt;/em&gt; is your most indispensable and versatile selling tool. The wide range of products included in this convenient, digest-size catalog will give you the ability to satisfy a variety of your customers’ needs..
        /// </summary>
        public static string ProductSpectrum {
            get {
                return ResourceManager.GetString("ProductSpectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Introducing Spectrum Celebration!&lt;/strong&gt; Our best-selling end-buyer catalog is now available in a summer/fall edition. It includes a special SELECT section featuring the top rated 4 star and up suppliers as well as a customer favorites section too..
        /// </summary>
        public static string ProductSpectrumCelebration {
            get {
                return ResourceManager.GetString("ProductSpectrumCelebration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stitches is the ultimate resource for commercial embroiderers and apparel decorators..
        /// </summary>
        public static string ProductStitches {
            get {
                return ResourceManager.GetString("ProductStitches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stitches is published 10x a year, with a circulation of 21,250..
        /// </summary>
        public static string ProductStitchesAdvertising {
            get {
                return ResourceManager.GetString("ProductStitchesAdvertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazines product - Promotions.
        /// </summary>
        public static string ProductSuccessfulPromotionsMagazine {
            get {
                return ResourceManager.GetString("ProductSuccessfulPromotionsMagazine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazines product - Promotions Special Offer.
        /// </summary>
        public static string ProductSuccessfulPromotionsMagazineSpecialOffer {
            get {
                return ResourceManager.GetString("ProductSuccessfulPromotionsMagazineSpecialOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazines product - Promotions Special Offer Dallas.
        /// </summary>
        public static string ProductSuccessfulPromotionsMagazineSpecialOfferDallas {
            get {
                return ResourceManager.GetString("ProductSuccessfulPromotionsMagazineSpecialOfferDallas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Event Planner offers one-stop shopping for distributors looking for event merchandise.  All events are listed on the ESP™ homepage providing instant accessibility, homepage visibility, and unlimited views. This new feature fully integrates the event concept and incorporates selling themed products within a pricing tier. Never before has it been so easy to sell a full package of products within a selected price range..
        /// </summary>
        public static string ProductTheEventPlanner {
            get {
                return ResourceManager.GetString("ProductTheEventPlanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogs product - The Gift Book.
        /// </summary>
        public static string ProductTheGiftBook {
            get {
                return ResourceManager.GetString("ProductTheGiftBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our most upscale, elegant catalog containing an impressive collection of timeless gifts All items are carefully and beautifully displayed to appeal to even the most sophisticated buyers..
        /// </summary>
        public static string ProductTheGiftBook2 {
            get {
                return ResourceManager.GetString("ProductTheGiftBook2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogs product - The Green Catalog.
        /// </summary>
        public static string ProductTheGreenCatalog {
            get {
                return ResourceManager.GetString("ProductTheGreenCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;em&gt;The Professional Buyer&apos;s Guide&lt;/em&gt; is your go-to catalogue for the Canadian marketplace. This catalogue contains only the most preferred and best suppliers in the Canadian market, offering a wide variety of products with no duplication..
        /// </summary>
        public static string ProductTheProfessionalBuyersGuide {
            get {
                return ResourceManager.GetString("ProductTheProfessionalBuyersGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By presenting your products in both mediums with an ESP video, a much stronger and memorable message will be delivered to your potential or existing customer base..
        /// </summary>
        public static string ProductVideo {
            get {
                return ResourceManager.GetString("ProductVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wearables is designed for today&apos;s busy apparel business owner..
        /// </summary>
        public static string ProductWearables {
            get {
                return ResourceManager.GetString("ProductWearables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wearables is published 10x a year, with a circulation of 15,000. Wearables is read by screen-printers and distributors..
        /// </summary>
        public static string ProductWearablesAdvertising {
            get {
                return ResourceManager.GetString("ProductWearablesAdvertising", resourceCulture);
            }
        }
    }
}
