using asi.asicentral.model.store;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using asi.asicentral.interfaces;
using System.Web.Mvc;
using asi.asicentral.Resources;
using System.Globalization;

namespace asi.asicentral.util.store
{
    public class MagazinesHelper
    {
        public const string HALLMARK_USA = "-80";
        public static IList<SelectListItem> GetCountriesForWearables(string value = null)
        {
            IList<SelectListItem> countries = new List<SelectListItem>();
            countries.Add(new SelectListItem { Text = "-- Select a Country --", Value = "", Selected = true });
            countries.Add(new SelectListItem { Text = "UNITED STATES", Value = "-80" });
            countries.Add(new SelectListItem { Text = "CANADA", Value = "-81" });
            countries.Add(new SelectListItem { Text = "AFGHANISTAN", Value = "-84" });
            countries.Add(new SelectListItem { Text = "AL HUCEMAS IS", Value = "-85" });
            countries.Add(new SelectListItem { Text = "ALBANIA", Value = "-86" });
            countries.Add(new SelectListItem { Text = "ALGERIA", Value = "-87" });
            countries.Add(new SelectListItem { Text = "ANDAMAN IS", Value = "-88" });
            countries.Add(new SelectListItem { Text = "ANDORRA", Value = "-89" });
            countries.Add(new SelectListItem { Text = "ANGOLA", Value = "-90" });
            countries.Add(new SelectListItem { Text = "ANGUILLA", Value = "-91" });
            countries.Add(new SelectListItem { Text = "ANTIGUA", Value = "-92" });
            countries.Add(new SelectListItem { Text = "ARGENTINA", Value = "-93" });
            countries.Add(new SelectListItem { Text = "ARMENIA", Value = "-94" });
            countries.Add(new SelectListItem { Text = "ARUBA", Value = "-95" });
            countries.Add(new SelectListItem { Text = "ASCENSION IS", Value = "-96" });
            countries.Add(new SelectListItem { Text = "AUSTRALIA", Value = "-97" });
            countries.Add(new SelectListItem { Text = "AUSTRIA", Value = "-98" });
            countries.Add(new SelectListItem { Text = "AZERBAIJAN", Value = "-99" });
            countries.Add(new SelectListItem { Text = "AZORES IS", Value = "-100" });
            countries.Add(new SelectListItem { Text = "BAHAMAS", Value = "-101" });
            countries.Add(new SelectListItem { Text = "BAHRAIN", Value = "-102" });
            countries.Add(new SelectListItem { Text = "BANGLADESH", Value = "-103" });
            countries.Add(new SelectListItem { Text = "BARBADOS", Value = "-104" });
            countries.Add(new SelectListItem { Text = "BARBUDA", Value = "-105" });
            countries.Add(new SelectListItem { Text = "BELARUS", Value = "-106" });
            countries.Add(new SelectListItem { Text = "BELEARIC IS", Value = "-107" });
            countries.Add(new SelectListItem { Text = "BELGIUM", Value = "-108" });
            countries.Add(new SelectListItem { Text = "BELIZE", Value = "-109" });
            countries.Add(new SelectListItem { Text = "BENIN", Value = "-110" });
            countries.Add(new SelectListItem { Text = "BERMUDA", Value = "-111" });
            countries.Add(new SelectListItem { Text = "BHUTAN", Value = "-112" });
            countries.Add(new SelectListItem { Text = "BOLIVIA", Value = "-113" });
            countries.Add(new SelectListItem { Text = "BORNEO", Value = "-114" });
            countries.Add(new SelectListItem { Text = "BOSNIA-HERZEGOVINA", Value = "-115" });
            countries.Add(new SelectListItem { Text = "BOTSWANA", Value = "-116" });
            countries.Add(new SelectListItem { Text = "BRAZIL", Value = "-117" });
            countries.Add(new SelectListItem { Text = "BRITISH VIRGIN IS", Value = "-118" });
            countries.Add(new SelectListItem { Text = "BRITISH WEST INDIES", Value = "-119" });
            countries.Add(new SelectListItem { Text = "BRUNEI", Value = "-120" });
            countries.Add(new SelectListItem { Text = "BULGARIA", Value = "-121" });
            countries.Add(new SelectListItem { Text = "BURKINA FASO", Value = "-122" });
            countries.Add(new SelectListItem { Text = "BURUNDI", Value = "-123" });
            countries.Add(new SelectListItem { Text = "CAMBODIA", Value = "-124" });
            countries.Add(new SelectListItem { Text = "CAMEROON", Value = "-125" });
            countries.Add(new SelectListItem { Text = "CANARY ISLANDS", Value = "-126" });
            countries.Add(new SelectListItem { Text = "CAPE VERDE ISLANDS", Value = "-127" });
            countries.Add(new SelectListItem { Text = "CAYMAN ISLANDS", Value = "-128" });
            countries.Add(new SelectListItem { Text = "CENTRAL AFRICAN REP", Value = "-129" });
            countries.Add(new SelectListItem { Text = "CHAD", Value = "-130" });
            countries.Add(new SelectListItem { Text = "CHAFERINAS IS", Value = "-131" });
            countries.Add(new SelectListItem { Text = "CHANNEL IS", Value = "-132" });
            countries.Add(new SelectListItem { Text = "CHATHAM IS", Value = "-133" });
            countries.Add(new SelectListItem { Text = "CHILE", Value = "-134" });
            countries.Add(new SelectListItem { Text = "CHINA", Value = "-135" });
            countries.Add(new SelectListItem { Text = "COCO ISLAND", Value = "-136" });
            countries.Add(new SelectListItem { Text = "COLOMBIA", Value = "-137" });
            countries.Add(new SelectListItem { Text = "COMOROS", Value = "-138" });
            countries.Add(new SelectListItem { Text = "CONGO", Value = "-139" });
            countries.Add(new SelectListItem { Text = "COOK ISLANDS", Value = "-141" });
            countries.Add(new SelectListItem { Text = "COSTA RICA", Value = "-142" });
            countries.Add(new SelectListItem { Text = "CROATIA", Value = "-143" });
            countries.Add(new SelectListItem { Text = "CUBA", Value = "-144" });
            countries.Add(new SelectListItem { Text = "CYPRUS", Value = "-145" });
            countries.Add(new SelectListItem { Text = "CZECH REPUBLIC", Value = "-146" });
            countries.Add(new SelectListItem { Text = "DENMARK", Value = "-147" });
            countries.Add(new SelectListItem { Text = "DJIBOUTI", Value = "-148" });
            countries.Add(new SelectListItem { Text = "DOMINICA", Value = "-149" });
            countries.Add(new SelectListItem { Text = "DOMINICAN REPUBLIC", Value = "-150" });
            countries.Add(new SelectListItem { Text = "EAST TIMOR", Value = "-151" });
            countries.Add(new SelectListItem { Text = "ECUADOR", Value = "-152" });
            countries.Add(new SelectListItem { Text = "EGYPT", Value = "-153" });
            countries.Add(new SelectListItem { Text = "EL SALVADOR", Value = "-154" });
            countries.Add(new SelectListItem { Text = "ENGLAND", Value = "-155" });
            countries.Add(new SelectListItem { Text = "ERITREA", Value = "-156" });
            countries.Add(new SelectListItem { Text = "ESTONIA", Value = "-157" });
            countries.Add(new SelectListItem { Text = "ETHIOPIA", Value = "-158" });
            countries.Add(new SelectListItem { Text = "FAEROE ISLANDS", Value = "-159" });
            countries.Add(new SelectListItem { Text = "FALKLAND ISLANDS", Value = "-160" });
            countries.Add(new SelectListItem { Text = "FIJI", Value = "-161" });
            countries.Add(new SelectListItem { Text = "FINLAND", Value = "-162" });
            countries.Add(new SelectListItem { Text = "FRANCE", Value = "-163" });
            countries.Add(new SelectListItem { Text = "FRENCH GUIANA", Value = "-164" });
            countries.Add(new SelectListItem { Text = "FRENCH POLYNESIA", Value = "-165" });
            countries.Add(new SelectListItem { Text = "FRENCH WEST INDIES", Value = "-166" });
            countries.Add(new SelectListItem { Text = "FUTUNA ISLANDS", Value = "-167" });
            countries.Add(new SelectListItem { Text = "GABON", Value = "-168" });
            countries.Add(new SelectListItem { Text = "GAMBIA", Value = "-169" });
            countries.Add(new SelectListItem { Text = "GAZA STRIP", Value = "-170" });
            countries.Add(new SelectListItem { Text = "GEORGIA", Value = "-171" });
            countries.Add(new SelectListItem { Text = "GERMANY", Value = "-172" });
            countries.Add(new SelectListItem { Text = "GHANA", Value = "-173" });
            countries.Add(new SelectListItem { Text = "GIBRALTAR", Value = "-174" });
            countries.Add(new SelectListItem { Text = "GILBERT IS", Value = "-175" });
            countries.Add(new SelectListItem { Text = "GREECE", Value = "-176" });
            countries.Add(new SelectListItem { Text = "GREENLAND", Value = "-177" });
            countries.Add(new SelectListItem { Text = "GRENADA", Value = "-178" });
            countries.Add(new SelectListItem { Text = "GUADELOUPE", Value = "-179" });
            countries.Add(new SelectListItem { Text = "GUATEMALA", Value = "-180" });
            countries.Add(new SelectListItem { Text = "GUERNSEY", Value = "-181" });
            countries.Add(new SelectListItem { Text = "GUINEA", Value = "-182" });
            countries.Add(new SelectListItem { Text = "GUYANA", Value = "-183" });
            countries.Add(new SelectListItem { Text = "HAITI", Value = "-184" });
            countries.Add(new SelectListItem { Text = "HONDURAS", Value = "-185" });
            countries.Add(new SelectListItem { Text = "HONG KONG", Value = "-186" });
            countries.Add(new SelectListItem { Text = "HUNGARY", Value = "-187" });
            countries.Add(new SelectListItem { Text = "ICELAND", Value = "-188" });
            countries.Add(new SelectListItem { Text = "INDIA", Value = "-189" });
            countries.Add(new SelectListItem { Text = "INDONESIA", Value = "-190" });
            countries.Add(new SelectListItem { Text = "IRAN", Value = "-191" });
            countries.Add(new SelectListItem { Text = "IRAQ", Value = "-192" });
            countries.Add(new SelectListItem { Text = "IRELAND", Value = "-193" });
            countries.Add(new SelectListItem { Text = "ISLE OF MAN", Value = "-194" });
            countries.Add(new SelectListItem { Text = "ISRAEL", Value = "-195" });
            countries.Add(new SelectListItem { Text = "ITALY", Value = "-196" });
            countries.Add(new SelectListItem { Text = "IVORY COAST", Value = "-197" });
            countries.Add(new SelectListItem { Text = "JAMAICA", Value = "-198" });
            countries.Add(new SelectListItem { Text = "JAPAN", Value = "-199" });
            countries.Add(new SelectListItem { Text = "JORDAN", Value = "-200" });
            countries.Add(new SelectListItem { Text = "KAZAKHSTAN", Value = "-201" });
            countries.Add(new SelectListItem { Text = "KENYA", Value = "-202" });
            countries.Add(new SelectListItem { Text = "KIRGHIZIA", Value = "-203" });
            countries.Add(new SelectListItem { Text = "KIRIBATI", Value = "-204" });
            countries.Add(new SelectListItem { Text = "KOSOVO", Value = "-205" });
            countries.Add(new SelectListItem { Text = "KUWAIT", Value = "-206" });
            countries.Add(new SelectListItem { Text = "KYRGYZSTAN", Value = "-207" });
            countries.Add(new SelectListItem { Text = "LAOS", Value = "-208" });
            countries.Add(new SelectListItem { Text = "LATVIA", Value = "-209" });
            countries.Add(new SelectListItem { Text = "LEBANON", Value = "-210" });
            countries.Add(new SelectListItem { Text = "LESOTHO", Value = "-211" });
            countries.Add(new SelectListItem { Text = "LIBERIA", Value = "-212" });
            countries.Add(new SelectListItem { Text = "LIBYA", Value = "-213" });
            countries.Add(new SelectListItem { Text = "LIECHTENSTEIN", Value = "-214" });
            countries.Add(new SelectListItem { Text = "LITHUANIA", Value = "-215" });
            countries.Add(new SelectListItem { Text = "LUXEMBOURG", Value = "-216" });
            countries.Add(new SelectListItem { Text = "MACAO", Value = "-217" });
            countries.Add(new SelectListItem { Text = "MACEDONIA", Value = "-218" });
            countries.Add(new SelectListItem { Text = "MADAGASCAR", Value = "-219" });
            countries.Add(new SelectListItem { Text = "MALAGASY", Value = "-220" });
            countries.Add(new SelectListItem { Text = "MALAWI", Value = "-221" });
            countries.Add(new SelectListItem { Text = "MALAYSIA", Value = "-222" });
            countries.Add(new SelectListItem { Text = "MALDIVES", Value = "-223" });
            countries.Add(new SelectListItem { Text = "MALI", Value = "-224" });
            countries.Add(new SelectListItem { Text = "MALTA", Value = "-225" });
            countries.Add(new SelectListItem { Text = "MARSHALL ISLANDS", Value = "-226" });
            countries.Add(new SelectListItem { Text = "MARTINIQUE", Value = "-227" });
            countries.Add(new SelectListItem { Text = "MAURITANIA", Value = "-228" });
            countries.Add(new SelectListItem { Text = "MAURITIUS", Value = "-229" });
            countries.Add(new SelectListItem { Text = "MAYOTTE", Value = "-230" });
            countries.Add(new SelectListItem { Text = "MEXICO", Value = "-231" });
            countries.Add(new SelectListItem { Text = "MICRONESIA", Value = "-232" });
            countries.Add(new SelectListItem { Text = "MOLDOVA", Value = "-233" });
            countries.Add(new SelectListItem { Text = "MOLUCA IS", Value = "-234" });
            countries.Add(new SelectListItem { Text = "MONACO", Value = "-235" });
            countries.Add(new SelectListItem { Text = "MONGOLIA", Value = "-236" });
            countries.Add(new SelectListItem { Text = "MONTENEGRO", Value = "-237" });
            countries.Add(new SelectListItem { Text = "MONTSERRAT", Value = "-238" });
            countries.Add(new SelectListItem { Text = "MOROCCO", Value = "-239" });
            countries.Add(new SelectListItem { Text = "MOZAMBIQUE", Value = "-240" });
            countries.Add(new SelectListItem { Text = "MYANMAR", Value = "-241" });
            countries.Add(new SelectListItem { Text = "NAMIBIA", Value = "-242" });
            countries.Add(new SelectListItem { Text = "NAURU", Value = "-243" });
            countries.Add(new SelectListItem { Text = "NEPAL", Value = "-244" });
            countries.Add(new SelectListItem { Text = "NETHERLAND ANTILLES", Value = "-245" });
            countries.Add(new SelectListItem { Text = "NETHERLANDS", Value = "-246" });
            countries.Add(new SelectListItem { Text = "NEVIS", Value = "-247" });
            countries.Add(new SelectListItem { Text = "NEW CALEDONIA", Value = "-248" });
            countries.Add(new SelectListItem { Text = "NEW GUINEA", Value = "-249" });
            countries.Add(new SelectListItem { Text = "NEW ZEALAND", Value = "-250" });
            countries.Add(new SelectListItem { Text = "NICARAGUA", Value = "-251" });
            countries.Add(new SelectListItem { Text = "NIGER", Value = "-252" });
            countries.Add(new SelectListItem { Text = "NIGERIA", Value = "-253" });
            countries.Add(new SelectListItem { Text = "NORTH KOREA", Value = "-254" });
            countries.Add(new SelectListItem { Text = "NORTHERN IRELAND", Value = "-255" });
            countries.Add(new SelectListItem { Text = "NORWAY", Value = "-256" });
            countries.Add(new SelectListItem { Text = "OMAN", Value = "-257" });
            countries.Add(new SelectListItem { Text = "ORKNEY IS", Value = "-258" });
            countries.Add(new SelectListItem { Text = "PAKISTAN", Value = "-259" });
            countries.Add(new SelectListItem { Text = "PALAU", Value = "-260" });
            countries.Add(new SelectListItem { Text = "PALESTINE", Value = "-261" });
            countries.Add(new SelectListItem { Text = "PANAMA", Value = "-262" });
            countries.Add(new SelectListItem { Text = "PARACEL ISLANDS", Value = "-263" });
            countries.Add(new SelectListItem { Text = "PARAGUAY", Value = "-264" });
            countries.Add(new SelectListItem { Text = "PERU", Value = "-265" });
            countries.Add(new SelectListItem { Text = "PHILIPPINES", Value = "-266" });
            countries.Add(new SelectListItem { Text = "PHOENIX IS", Value = "-267" });
            countries.Add(new SelectListItem { Text = "PITCAIRN IS", Value = "-268" });
            countries.Add(new SelectListItem { Text = "POLAND", Value = "-269" });
            countries.Add(new SelectListItem { Text = "PORTUGAL", Value = "-270" });
            countries.Add(new SelectListItem { Text = "QATAR", Value = "-271" });
            countries.Add(new SelectListItem { Text = "REUNION", Value = "-272" });
            countries.Add(new SelectListItem { Text = "ROMANIA", Value = "-273" });
            countries.Add(new SelectListItem { Text = "RUSSIA", Value = "-274" });
            countries.Add(new SelectListItem { Text = "RWANDA", Value = "-275" });
            countries.Add(new SelectListItem { Text = "SAN MARINO", Value = "-276" });
            countries.Add(new SelectListItem { Text = "SAO TOME E PRINCIPE", Value = "-277" });
            countries.Add(new SelectListItem { Text = "SARAWAK", Value = "-278" });
            countries.Add(new SelectListItem { Text = "SAUDI ARABIA", Value = "-279" });
            countries.Add(new SelectListItem { Text = "SCOTLAND", Value = "-280" });
            countries.Add(new SelectListItem { Text = "SENEGAL", Value = "-281" });
            countries.Add(new SelectListItem { Text = "SERBIA", Value = "-282" });
            countries.Add(new SelectListItem { Text = "SEYCHELLES", Value = "-283" });
            countries.Add(new SelectListItem { Text = "SIERRA LEONE", Value = "-284" });
            countries.Add(new SelectListItem { Text = "SINGAPORE", Value = "-285" });
            countries.Add(new SelectListItem { Text = "SLOVAK REPUBLIC", Value = "-286" });
            countries.Add(new SelectListItem { Text = "SLOVENIA", Value = "-287" });
            countries.Add(new SelectListItem { Text = "SOLOMON ISLANDS", Value = "-288" });
            countries.Add(new SelectListItem { Text = "SOMALIA", Value = "-289" });
            countries.Add(new SelectListItem { Text = "SOUTH AFRICA", Value = "-290" });
            countries.Add(new SelectListItem { Text = "SOUTH KOREA", Value = "-291" });
            countries.Add(new SelectListItem { Text = "SPAIN", Value = "-292" });
            countries.Add(new SelectListItem { Text = "SRI LANKA", Value = "-293" });
            countries.Add(new SelectListItem { Text = "ST CROIX", Value = "-294" });
            countries.Add(new SelectListItem { Text = "ST KITTS", Value = "-295" });
            countries.Add(new SelectListItem { Text = "ST LUCIA", Value = "-296" });
            countries.Add(new SelectListItem { Text = "ST MAARTEN", Value = "-297" });
            countries.Add(new SelectListItem { Text = "ST MARTIN", Value = "-298" });
            countries.Add(new SelectListItem { Text = "ST PIERRE", Value = "-299" });
            countries.Add(new SelectListItem { Text = "ST VINCENT", Value = "-300" });
            countries.Add(new SelectListItem { Text = "SUDAN", Value = "-301" });
            countries.Add(new SelectListItem { Text = "SURINAME", Value = "-302" });
            countries.Add(new SelectListItem { Text = "SWAZILAND", Value = "-303" });
            countries.Add(new SelectListItem { Text = "SWEDEN", Value = "-304" });
            countries.Add(new SelectListItem { Text = "SWITZERLAND", Value = "-305" });
            countries.Add(new SelectListItem { Text = "SYRIA", Value = "-306" });
            countries.Add(new SelectListItem { Text = "TAHITI", Value = "-307" });
            countries.Add(new SelectListItem { Text = "TAIWAN", Value = "-308" });
            countries.Add(new SelectListItem { Text = "TAJIKISTAN", Value = "-309" });
            countries.Add(new SelectListItem { Text = "TANZANIA", Value = "-310" });
            countries.Add(new SelectListItem { Text = "TASMANIA", Value = "-311" });
            countries.Add(new SelectListItem { Text = "THAILAND", Value = "-312" });
            countries.Add(new SelectListItem { Text = "TIBET", Value = "-313" });
            countries.Add(new SelectListItem { Text = "TOGO", Value = "-314" });
            countries.Add(new SelectListItem { Text = "TONGA", Value = "-315" });
            countries.Add(new SelectListItem { Text = "TRINIDAD AND TOBAGO", Value = "-316" });
            countries.Add(new SelectListItem { Text = "TUNISIA", Value = "-317" });
            countries.Add(new SelectListItem { Text = "TURKEY", Value = "-318" });
            countries.Add(new SelectListItem { Text = "TURKMENISTAN", Value = "-319" });
            countries.Add(new SelectListItem { Text = "TURKS ISLAND", Value = "-320" });
            countries.Add(new SelectListItem { Text = "TUVALU", Value = "-321" });
            countries.Add(new SelectListItem { Text = "UGANDA", Value = "-322" });
            countries.Add(new SelectListItem { Text = "UKRAINE", Value = "-323" });
            countries.Add(new SelectListItem { Text = "UNITED ARAB EMIRATES", Value = "-324" });
            countries.Add(new SelectListItem { Text = "URUGUAY", Value = "-325" });
            countries.Add(new SelectListItem { Text = "UZBEKISTAN", Value = "-326" });
            countries.Add(new SelectListItem { Text = "VANUATU", Value = "-327" });
            countries.Add(new SelectListItem { Text = "VATICAN CITY", Value = "-328" });
            countries.Add(new SelectListItem { Text = "VENEZUELA", Value = "-329" });
            countries.Add(new SelectListItem { Text = "VIETNAM", Value = "-330" });
            countries.Add(new SelectListItem { Text = "WALES", Value = "-331" });
            countries.Add(new SelectListItem { Text = "WALLIS ISLAND", Value = "-332" });
            countries.Add(new SelectListItem { Text = "WESTERN SAHARA", Value = "-333" });
            countries.Add(new SelectListItem { Text = "WESTERN SAMOA", Value = "-334" });
            countries.Add(new SelectListItem { Text = "YEMEN", Value = "-335" });
            countries.Add(new SelectListItem { Text = "ZAIRE", Value = "-336" });
            countries.Add(new SelectListItem { Text = "ZAMBIA", Value = "-337" });
            countries.Add(new SelectListItem { Text = "ZIMBABWE", Value = "-338" });
            countries.Add(new SelectListItem { Text = "ANTARCTICA", Value = "-350" });
            countries.Add(new SelectListItem { Text = "BRIT INDIAN OCN TERR", Value = "-351" });
            countries.Add(new SelectListItem { Text = "UNITED KINGDOM", Value = "-749" });
            return countries;
        }

        public static string GetHallmarkCountryName(string value)
        {
            IList<SelectListItem> countries = GetCountriesForWearables();
            string country = countries.Where(c => c.Value == value).First().Text;
            TextInfo textInfo = new CultureInfo("en-US", false).TextInfo;
            return textInfo.ToTitleCase(country.ToLower());
        }

        public static IList<SelectListItem> GetStatesForWearables(string value = null)
        {
            IList<SelectListItem> states = new List<SelectListItem>();
            states.Add(new SelectListItem { Text = "-- Select a State --", Value = "", Selected = true });
            states.Add(new SelectListItem() { Text = "ALABAMA", Value = "-1~AL" });
            states.Add(new SelectListItem() { Text = "ALASKA", Value = "-2~AK" });
            states.Add(new SelectListItem() { Text = "ARIZONA", Value = "-3~AZ" });
            states.Add(new SelectListItem() { Text = "ARKANSAS", Value = "-4~AR" });
            states.Add(new SelectListItem() { Text = "CALIFORNIA", Value = "-5~CA" });
            states.Add(new SelectListItem() { Text = "COLORADO", Value = "-6~CO" });
            states.Add(new SelectListItem() { Text = "CONNECTICUT", Value = "-7~CT" });
            states.Add(new SelectListItem() { Text = "DELAWARE", Value = "-8~DE" });
            states.Add(new SelectListItem() { Text = "DISTRICT OF COLUMBIA", Value = "-9~DC" });
            states.Add(new SelectListItem() { Text = "FLORIDA", Value = "-10~FL" });
            states.Add(new SelectListItem() { Text = "GEORGIA", Value = "-11~GA" });
            states.Add(new SelectListItem() { Text = "HAWAII", Value = "-12~HI" });
            states.Add(new SelectListItem() { Text = "IDAHO", Value = "-13~ID" });
            states.Add(new SelectListItem() { Text = "ILLINOIS", Value = "-14~IL" });
            states.Add(new SelectListItem() { Text = "INDIANA", Value = "-15~IN" });
            states.Add(new SelectListItem() { Text = "IOWA", Value = "-16~IA" });
            states.Add(new SelectListItem() { Text = "KANSAS", Value = "-17~KS" });
            states.Add(new SelectListItem() { Text = "KENTUCKY", Value = "-18~KY" });
            states.Add(new SelectListItem() { Text = "LOUISIANA", Value = "-19~LA" });
            states.Add(new SelectListItem() { Text = "MAINE", Value = "-20~ME" });
            states.Add(new SelectListItem() { Text = "MARYLAND", Value = "-21~MD" });
            states.Add(new SelectListItem() { Text = "MASSACHUSETTS", Value = "-22~MA" });
            states.Add(new SelectListItem() { Text = "MICHIGAN", Value = "-23~MI" });
            states.Add(new SelectListItem() { Text = "MINNESOTA", Value = "-24~MN" });
            states.Add(new SelectListItem() { Text = "MISSISSIPPI", Value = "-25~MS" });
            states.Add(new SelectListItem() { Text = "MISSOURI", Value = "-26~MO" });
            states.Add(new SelectListItem() { Text = "MONTANA", Value = "-27~MT" });
            states.Add(new SelectListItem() { Text = "NEBRASKA", Value = "-28~NE" });
            states.Add(new SelectListItem() { Text = "NEVADA", Value = "-29~NV" });
            states.Add(new SelectListItem() { Text = "NEW HAMPSHIRE", Value = "-30~NH" });
            states.Add(new SelectListItem() { Text = "NEW JERSEY", Value = "-31~NJ" });
            states.Add(new SelectListItem() { Text = "NEW MEXICO", Value = "-32~NM" });
            states.Add(new SelectListItem() { Text = "NEW YORK", Value = "-33~NY" });
            states.Add(new SelectListItem() { Text = "NORTH CAROLINA", Value = "-34~NC" });
            states.Add(new SelectListItem() { Text = "NORTH DAKOTA", Value = "-35~ND" });
            states.Add(new SelectListItem() { Text = "OHIO", Value = "-36~OH" });
            states.Add(new SelectListItem() { Text = "OKLAHOMA", Value = "-37~OK" });
            states.Add(new SelectListItem() { Text = "OREGON", Value = "-38~OR" });
            states.Add(new SelectListItem() { Text = "PENNSYLVANIA", Value = "-39~PA" });
            states.Add(new SelectListItem() { Text = "RHODE ISLAND", Value = "-40~RI" });
            states.Add(new SelectListItem() { Text = "SOUTH CAROLINA", Value = "-41~SC" });
            states.Add(new SelectListItem() { Text = "SOUTH DAKOTA", Value = "-42~SD" });
            states.Add(new SelectListItem() { Text = "TENNESSEE", Value = "-43~TN" });
            states.Add(new SelectListItem() { Text = "TEXAS", Value = "-44~TX" });
            states.Add(new SelectListItem() { Text = "UTAH", Value = "-45~UT" });
            states.Add(new SelectListItem() { Text = "VERMONT", Value = "-46~VT" });
            states.Add(new SelectListItem() { Text = "VIRGIN ISLANDS", Value = "-47~VI" });
            states.Add(new SelectListItem() { Text = "VIRGINIA", Value = "-48~VA" });
            states.Add(new SelectListItem() { Text = "WASHINGTON", Value = "-49~WA" });
            states.Add(new SelectListItem() { Text = "WEST VIRGINIA", Value = "-50~WV" });
            states.Add(new SelectListItem() { Text = "WISCONSIN", Value = "-51~WI" });
            states.Add(new SelectListItem() { Text = "WYOMING", Value = "-52~WY" });
            states.Add(new SelectListItem() { Text = "American Samoa", Value = "-53~AS" });
            states.Add(new SelectListItem() { Text = "Guam", Value = "-54~GU" });
            states.Add(new SelectListItem() { Text = "Marshall Islands", Value = "-55~MH" });
            states.Add(new SelectListItem() { Text = "Micronesia (Federated States of)", Value = "-56~FM" });
            states.Add(new SelectListItem() { Text = "Palau", Value = "-57~PW" });
            states.Add(new SelectListItem() { Text = "Puerto Rico", Value = "-58~PR" });
            states.Add(new SelectListItem() { Text = "U.S. Minor Outlying Islands", Value = "-59~OL" });
            states.Add(new SelectListItem() { Text = "NORTHERN MARIANA ISLANDS", Value = "-60~GU" });
            states.Add(new SelectListItem() { Text = "Armed Forces Africa", Value = "-61~AE" });
            states.Add(new SelectListItem() { Text = "Armed Forces Americas AA (except Canada)", Value = "-62~AA" });
            states.Add(new SelectListItem() { Text = "Armed Forces Canada", Value = "-63~AE" });
            states.Add(new SelectListItem() { Text = "Armed Forces Europe AE", Value = "-64~AE" });
            states.Add(new SelectListItem() { Text = "Armed Forces Middle East AE", Value = "-65~AE" });
            states.Add(new SelectListItem() { Text = "Armed Forces Pacific AP", Value = "-66~AP" });
            states.Add(new SelectListItem() { Text = "ALBERTA", Value = "-67~AB" });
            states.Add(new SelectListItem() { Text = "NOVA SCOTIA", Value = "-68~NS" });
            states.Add(new SelectListItem() { Text = "BRITISH COLUMBIA", Value = "-69~BC" });
            states.Add(new SelectListItem() { Text = "ONTARIO", Value = "-70~ON" });
            states.Add(new SelectListItem() { Text = "MANITOBA", Value = "-71~MB" });
            states.Add(new SelectListItem() { Text = "PRINCE EDWARD ISLAND", Value = "-72~PE" });
            states.Add(new SelectListItem() { Text = "NEW BRUNSWICK", Value = "-73~NB" });
            states.Add(new SelectListItem() { Text = "QUEBEC", Value = "-74~QC" });
            states.Add(new SelectListItem() { Text = "NEWFOUNDLAND", Value = "-75~NL" });
            states.Add(new SelectListItem() { Text = "SASKATCHEWAN", Value = "-76~SK" });
            states.Add(new SelectListItem() { Text = "NORTHWEST TERRITORIES", Value = "-77~NT" });
            states.Add(new SelectListItem() { Text = "YUKON TERRITORY", Value = "-78~YT" });
            states.Add(new SelectListItem() { Text = "NUNAVUT", Value = "-79~NU" });
            return states;
        }
    }
}
