//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asi.asicentral {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("asi.asicentral.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliate ASI Number.
        /// </summary>
        public static string AffiliateASINumber {
            get {
                return ResourceManager.GetString("AffiliateASINumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliate Company Name.
        /// </summary>
        public static string AffiliateCompanyName {
            get {
                return ResourceManager.GetString("AffiliateCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the terms and conditions.
        /// </summary>
        public static string AgreeASITermsAndConditions {
            get {
                return ResourceManager.GetString("AgreeASITermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreed to recieve promotion products?.
        /// </summary>
        public static string AgreeReceivePromotionalProducts {
            get {
                return ResourceManager.GetString("AgreeReceivePromotionalProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree to the terms and condition?.
        /// </summary>
        public static string AgreeTermsAndConditions {
            get {
                return ResourceManager.GetString("AgreeTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I hereby request and authorize ASI to open a UPS® account for my company to take advantage of the ASI shipping program incentives. I understand the shipping incentives will begin 10 working days after I receive my ASI number and there are no other incentives available to my existing UPS® account number..
        /// </summary>
        public static string AgreeUPSTermsAndConditions {
            get {
                return ResourceManager.GetString("AgreeUPSTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Sales Volume.
        /// </summary>
        public static string AnnualSalesVolume {
            get {
                return ResourceManager.GetString("AnnualSalesVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Sales Volume ASP.
        /// </summary>
        public static string AnnualSalesVolumeASP {
            get {
                return ResourceManager.GetString("AnnualSalesVolumeASP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant Email address.
        /// </summary>
        public static string ApplicantEmail {
            get {
                return ResourceManager.GetString("ApplicantEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual’s Name (filling out the online form):.
        /// </summary>
        public static string ApplicantName {
            get {
                return ResourceManager.GetString("ApplicantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Status.
        /// </summary>
        public static string ApplicationStatus {
            get {
                return ResourceManager.GetString("ApplicationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASI Contact.
        /// </summary>
        public static string ASIContact {
            get {
                return ResourceManager.GetString("ASIContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASI Number.
        /// </summary>
        public static string ASINumber {
            get {
                return ResourceManager.GetString("ASINumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize UPS New Account.
        /// </summary>
        public static string AuthorizeUPSNewAccount {
            get {
                return ResourceManager.GetString("AuthorizeUPSNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Ad.
        /// </summary>
        public static string BannerAd {
            get {
                return ResourceManager.GetString("BannerAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        public static string BillingAddress {
            get {
                return ResourceManager.GetString("BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing City.
        /// </summary>
        public static string BillingCity {
            get {
                return ResourceManager.GetString("BillingCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Email.
        /// </summary>
        public static string BillingEmail {
            get {
                return ResourceManager.GetString("BillingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Fax Number.
        /// </summary>
        public static string BillingFax {
            get {
                return ResourceManager.GetString("BillingFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Phone Number.
        /// </summary>
        public static string BillingPhone {
            get {
                return ResourceManager.GetString("BillingPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing State.
        /// </summary>
        public static string BillingState {
            get {
                return ResourceManager.GetString("BillingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Toll Free Phone.
        /// </summary>
        public static string BillingTollPhone {
            get {
                return ResourceManager.GetString("BillingTollPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Web URL.
        /// </summary>
        public static string BillingWebUrl {
            get {
                return ResourceManager.GetString("BillingWebUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Zipcode.
        /// </summary>
        public static string BillingZip {
            get {
                return ResourceManager.GetString("BillingZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buddy List $199/mo..
        /// </summary>
        public static string BuddyList_199 {
            get {
                return ResourceManager.GetString("BuddyList_199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Hours.
        /// </summary>
        public static string BusinessHours {
            get {
                return ResourceManager.GetString("BusinessHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy additional videos (to be shown across different product categories) $79/year.
        /// </summary>
        public static string BuyAdditionalVideo {
            get {
                return ResourceManager.GetString("BuyAdditionalVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy one video (to be shown with all of your products) $499/year.
        /// </summary>
        public static string BuyOneVideo {
            get {
                return ResourceManager.GetString("BuyOneVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Id.
        /// </summary>
        public static string CategoryID {
            get {
                return ResourceManager.GetString("CategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Sales Turnover.
        /// </summary>
        public static string CompanyAnnualSalesTurnover {
            get {
                return ResourceManager.GetString("CompanyAnnualSalesTurnover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buisness Type.
        /// </summary>
        public static string CompanyBusinessType {
            get {
                return ResourceManager.GetString("CompanyBusinessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Email.
        /// </summary>
        public static string CompanyContactEmail {
            get {
                return ResourceManager.GetString("CompanyContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string CompanyContactName {
            get {
                return ResourceManager.GetString("CompanyContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Id.
        /// </summary>
        public static string CompanyID {
            get {
                return ResourceManager.GetString("CompanyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is inactive?.
        /// </summary>
        public static string CompanyIsInactive {
            get {
                return ResourceManager.GetString("CompanyIsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Employees.
        /// </summary>
        public static string CompanyNumOfEmployees {
            get {
                return ResourceManager.GetString("CompanyNumOfEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Time.
        /// </summary>
        public static string CompanyProductionTime {
            get {
                return ResourceManager.GetString("CompanyProductionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Summary.
        /// </summary>
        public static string CompanySummary {
            get {
                return ResourceManager.GetString("CompanySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Url.
        /// </summary>
        public static string CompanyURL {
            get {
                return ResourceManager.GetString("CompanyURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am a corporate officer, partner, or owner of the company submitting the ASI memberapplication, and am authorized to do so..
        /// </summary>
        public static string CorporateOfficer {
            get {
                return ResourceManager.GetString("CorporateOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $125/month for 3 products.
        /// </summary>
        public static string Cost_300_5_Products_PerMonth {
            get {
                return ResourceManager.GetString("Cost_300_5_Products_PerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        public static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose at least one date.
        /// </summary>
        public static string EmailExpress_Error_Date {
            get {
                return ResourceManager.GetString("EmailExpress_Error_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one of the Email Express Option to proceed.
        /// </summary>
        public static string EmailExpress_Error_ItemType {
            get {
                return ResourceManager.GetString("EmailExpress_Error_ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept the Terms &amp; Conditions to proceed.
        /// </summary>
        public static string EmailExpress_Error_Terms {
            get {
                return ResourceManager.GetString("EmailExpress_Error_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailExpress Platinum.
        /// </summary>
        public static string EmailExpress_Platinum {
            get {
                return ResourceManager.GetString("EmailExpress_Platinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular EmailExpress.
        /// </summary>
        public static string EmailExpress_Regular {
            get {
                return ResourceManager.GetString("EmailExpress_Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected {x} date(s):.
        /// </summary>
        public static string EmailExpress_Selected_Dates_Count {
            get {
                return ResourceManager.GetString("EmailExpress_Selected_Dates_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Request.
        /// </summary>
        public static string EmailExpress_Special {
            get {
                return ResourceManager.GetString("EmailExpress_Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailExpress Targeted List.
        /// </summary>
        public static string EmailExpress_TargetedList {
            get {
                return ResourceManager.GetString("EmailExpress_TargetedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive.
        /// </summary>
        public static string Executive {
            get {
                return ResourceManager.GetString("Executive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Number.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Area Code.
        /// </summary>
        public static string FaxAreaCode {
            get {
                return ResourceManager.GetString("FaxAreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Country Code.
        /// </summary>
        public static string FaxCountryCode {
            get {
                return ResourceManager.GetString("FaxCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Extension.
        /// </summary>
        public static string FaxExt {
            get {
                return ResourceManager.GetString("FaxExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Federal Tax ID.
        /// </summary>
        public static string FedTaxId {
            get {
                return ResourceManager.GetString("FedTaxId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid ASI #..
        /// </summary>
        public static string FieldInvalidASINumber {
            get {
                return ResourceManager.GetString("FieldInvalidASINumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        public static string FieldInvalidEmail {
            get {
                return ResourceManager.GetString("FieldInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone number..
        /// </summary>
        public static string FieldInvalidNumber {
            get {
                return ResourceManager.GetString("FieldInvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is too long..
        /// </summary>
        public static string FieldLength {
            get {
                return ResourceManager.GetString("FieldLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Required.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a year between 1700 and 2050..
        /// </summary>
        public static string FieldYearRange {
            get {
                return ResourceManager.GetString("FieldYearRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has American Products.
        /// </summary>
        public static string HasAmericanProducts {
            get {
                return ResourceManager.GetString("HasAmericanProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the above conditions should change, I will inform ASI ofthe change..
        /// </summary>
        public static string InformASIOfChange {
            get {
                return ResourceManager.GetString("InformASIOfChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant Messenger $450/mo..
        /// </summary>
        public static string InstantMessenger_450 {
            get {
                return ResourceManager.GetString("InstantMessenger_450", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My company is a for-profit re-seller of advertising specialties,or related items, such as printed promotional items, trophies, awards, imprintedapparel, screen-printed or embroidered items, signs and other related items..
        /// </summary>
        public static string IsForProfit {
            get {
                return ResourceManager.GetString("IsForProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Importer.
        /// </summary>
        public static string IsImporter {
            get {
                return ResourceManager.GetString("IsImporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Imprinter/Decorator.
        /// </summary>
        public static string IsImprinterVsDecorator {
            get {
                return ResourceManager.GetString("IsImprinterVsDecorator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The majority (51%) of the advertising specialties the company plans to buy are forre-sale and not for my company nor for any person or a company affiliated with mycompany (other than as a paying customer)..
        /// </summary>
        public static string IsMajorForResale {
            get {
                return ResourceManager.GetString("IsMajorForResale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My company is a distributor/reseller of ad specialties or related business and isa for profit entity under U.S. state or federal law. The majority of ad specialtieswe distribute or will distribute are for re-sale to customers that are not owned,operated, controlled, franchised, affiliated, or connected to our company..
        /// </summary>
        public static string IsMajorityDistributeForResale {
            get {
                return ResourceManager.GetString("IsMajorityDistributeForResale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Manufacturer.
        /// </summary>
        public static string IsManufacturer {
            get {
                return ResourceManager.GetString("IsManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Retailer.
        /// </summary>
        public static string IsRetailer {
            get {
                return ResourceManager.GetString("IsRetailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Rush Service Available.
        /// </summary>
        public static string IsRushServiceAvailable {
            get {
                return ResourceManager.GetString("IsRushServiceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I work solely for the company applying for membership..
        /// </summary>
        public static string IsSolelyWork {
            get {
                return ResourceManager.GetString("IsSolelyWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Union Made.
        /// </summary>
        public static string IsUnionMade {
            get {
                return ResourceManager.GetString("IsUnionMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is UPS Available.
        /// </summary>
        public static string IsUPSAvailable {
            get {
                return ResourceManager.GetString("IsUPSAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Wholesaler.
        /// </summary>
        public static string IsWholesaler {
            get {
                return ResourceManager.GetString("IsWholesaler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Woman Owned.
        /// </summary>
        public static string IsWomanOwned {
            get {
                return ResourceManager.GetString("IsWomanOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Names.
        /// </summary>
        public static string LineNames {
            get {
                return ResourceManager.GetString("LineNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Chat Room $750/mo..
        /// </summary>
        public static string MainChatRoom_750 {
            get {
                return ResourceManager.GetString("MainChatRoom_750", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership.
        /// </summary>
        public static string Membership {
            get {
                return ResourceManager.GetString("Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Minority Owned.
        /// </summary>
        public static string MinorityOwned {
            get {
                return ResourceManager.GetString("MinorityOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Employee.
        /// </summary>
        public static string NumberOfEmployee {
            get {
                return ResourceManager.GetString("NumberOfEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Sales Employee.
        /// </summary>
        public static string NumberOfSalesEmployee {
            get {
                return ResourceManager.GetString("NumberOfSalesEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Hours.
        /// </summary>
        public static string OfficeHour {
            get {
                return ResourceManager.GetString("OfficeHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Office Hour End.
        /// </summary>
        public static string OfficeHourEnd {
            get {
                return ResourceManager.GetString("OfficeHourEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Business Revenue.
        /// </summary>
        public static string OtherBusinessRevenue {
            get {
                return ResourceManager.GetString("OtherBusinessRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Decorator.
        /// </summary>
        public static string OtherDec {
            get {
                return ResourceManager.GetString("OtherDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Area Code.
        /// </summary>
        public static string PhoneAreaCode {
            get {
                return ResourceManager.GetString("PhoneAreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Extension.
        /// </summary>
        public static string PhoneExt {
            get {
                return ResourceManager.GetString("PhoneExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Business.
        /// </summary>
        public static string PrimaryBusiness {
            get {
                return ResourceManager.GetString("PrimaryBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Business Other Description.
        /// </summary>
        public static string PrimaryBusinessOtherDescription {
            get {
                return ResourceManager.GetString("PrimaryBusinessOtherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Id.
        /// </summary>
        public static string ProductID {
            get {
                return ResourceManager.GetString("ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Time.
        /// </summary>
        public static string ProductionTime {
            get {
                return ResourceManager.GetString("ProductionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Inactive?.
        /// </summary>
        public static string ProductIsActive {
            get {
                return ResourceManager.GetString("ProductIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Specifications.
        /// </summary>
        public static string ProductKeySpecifications {
            get {
                return ResourceManager.GetString("ProductKeySpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Image.
        /// </summary>
        public static string ProductLargeImg {
            get {
                return ResourceManager.GetString("ProductLargeImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Order Quanity.
        /// </summary>
        public static string ProductMinOrderQuantity {
            get {
                return ResourceManager.GetString("ProductMinOrderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Number.
        /// </summary>
        public static string ProductModelNumber {
            get {
                return ResourceManager.GetString("ProductModelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Terms.
        /// </summary>
        public static string ProductPaymentTerms {
            get {
                return ResourceManager.GetString("ProductPaymentTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string ProductPrice {
            get {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Ceiling.
        /// </summary>
        public static string ProductPriceCeiling {
            get {
                return ResourceManager.GetString("ProductPriceCeiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Image.
        /// </summary>
        public static string ProductSmallImg {
            get {
                return ResourceManager.GetString("ProductSmallImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree that upon request, I will provide the number of invoicesand other information ASI requests in order to demonstrate that I am a re-sellerof advertising specialties or related items, such as printed promotional items,trophies, awards, imprinted apparel, screen-printed or embroidered items, signsand other related items consistent with membership requirements. I under stand thata failure to do so may result in the de-listing of the company as an ASI member..
        /// </summary>
        public static string ProvideInvoiceOnDemand {
            get {
                return ResourceManager.GetString("ProvideInvoiceOnDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Volume.
        /// </summary>
        public static string SalesVolume {
            get {
                return ResourceManager.GetString("SalesVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select number of products.
        /// </summary>
        public static string SelectNumberOfProducts {
            get {
                return ResourceManager.GetString("SelectNumberOfProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Through Affiliate.
        /// </summary>
        public static string SellThruAffiliate {
            get {
                return ResourceManager.GetString("SellThruAffiliate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Through Direct Marketing.
        /// </summary>
        public static string SellThruDirectMarketing {
            get {
                return ResourceManager.GetString("SellThruDirectMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Through Distributors.
        /// </summary>
        public static string SellThruDistributors {
            get {
                return ResourceManager.GetString("SellThruDistributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Through Internet.
        /// </summary>
        public static string SellThruInternet {
            get {
                return ResourceManager.GetString("SellThruInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Through Retail.
        /// </summary>
        public static string SellThruRetail {
            get {
                return ResourceManager.GetString("SellThruRetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell to End Users.
        /// </summary>
        public static string SellToEndUsers {
            get {
                return ResourceManager.GetString("SellToEndUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        public static string ShippingAddress {
            get {
                return ResourceManager.GetString("ShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconday Shipping Address.
        /// </summary>
        public static string ShippingAddress2 {
            get {
                return ResourceManager.GetString("ShippingAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping City.
        /// </summary>
        public static string ShippingCity {
            get {
                return ResourceManager.GetString("ShippingCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping State.
        /// </summary>
        public static string ShippingState {
            get {
                return ResourceManager.GetString("ShippingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Zipcode.
        /// </summary>
        public static string ShippingZip {
            get {
                return ResourceManager.GetString("ShippingZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Signatures.
        /// </summary>
        public static string SignatureType {
            get {
                return ResourceManager.GetString("SignatureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the answer to Question No. 5 is &quot;no&quot; what is the name ofthe other company you work for?.
        /// </summary>
        public static string SolelyWorkName {
            get {
                return ResourceManager.GetString("SolelyWorkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address .
        /// </summary>
        public static string Street1 {
            get {
                return ResourceManager.GetString("Street1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Street Address.
        /// </summary>
        public static string Street2 {
            get {
                return ResourceManager.GetString("Street2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Ad.
        /// </summary>
        public static string TitleAd {
            get {
                return ResourceManager.GetString("TitleAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tower Tuesday Ad.
        /// </summary>
        public static string TowerTuesdayAd {
            get {
                return ResourceManager.GetString("TowerTuesdayAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I certify that the answers I have provided above and in the ASI MembershipApplication are true and accurate. If ASI determines otherwise, I understand thatASI, in it sole discretion, may de-list my company as an ASI member..
        /// </summary>
        public static string TrueAnswers {
            get {
                return ResourceManager.GetString("TrueAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS 2nd Day.
        /// </summary>
        public static string UPS2Day {
            get {
                return ResourceManager.GetString("UPS2Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS Address.
        /// </summary>
        public static string UPSAddress {
            get {
                return ResourceManager.GetString("UPSAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS City.
        /// </summary>
        public static string UPSCity {
            get {
                return ResourceManager.GetString("UPSCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS Ground.
        /// </summary>
        public static string UPSGround {
            get {
                return ResourceManager.GetString("UPSGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS Overnight.
        /// </summary>
        public static string UPSOvernight {
            get {
                return ResourceManager.GetString("UPSOvernight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS Shipping Number.
        /// </summary>
        public static string UPSShippingNumber {
            get {
                return ResourceManager.GetString("UPSShippingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS State.
        /// </summary>
        public static string UPSState {
            get {
                return ResourceManager.GetString("UPSState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS Zip.
        /// </summary>
        public static string UPSZip {
            get {
                return ResourceManager.GetString("UPSZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Address.
        /// </summary>
        public static string WebUrl {
            get {
                return ResourceManager.GetString("WebUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Entered Advertising Specialty Industry.
        /// </summary>
        public static string YearEnteredAdvertising {
            get {
                return ResourceManager.GetString("YearEnteredAdvertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Established.
        /// </summary>
        public static string YearEst {
            get {
                return ResourceManager.GetString("YearEst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Established.
        /// </summary>
        public static string YearEstablished {
            get {
                return ResourceManager.GetString("YearEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipcode.
        /// </summary>
        public static string Zipcode {
            get {
                return ResourceManager.GetString("Zipcode", resourceCulture);
            }
        }
    }
}
