using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace asi.asicentral.web.Controllers
{
    public class ExceptionController : Controller
    {
        public ActionResult Generate()
        {
            throw new Exception("Exception Generated by the controller");
        }
    }
}
